kubewharf/kubegateway

MAINTAINERS.md
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind flake
docs: delete personal email address
NONE
NONE
=> docs: delete personal email address

pkg/gateway/metrics/metrics.go, pkg/gateway/proxy/dispatcher/dispatcher.go, pkg/gateway/proxy/dispatcher/proxylog.go
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind flake
/kind feature
feat: streamline metrics
NONE
NONE
```release-note
```
=> feat: streamline metrics

README.md, README.zh_CN.md
=> docs: format style

README.md
Readme hyperlink does not format with a space in between.
Fixes #
```release-note
NONE
```
=> fix readme hyperlink format

README.zh_CN.md
=> docs: readme format style

README.md
=> typo: mannually => manually

cmd/kube-gateway/app/proxy.go, pkg/gateway/endpoints/filters/termination.go, pkg/gateway/endpoints/request/proxyInfo.go, pkg/gateway/endpoints/request/requestinfo.go, pkg/gateway/proxy/dispatcher/dispatcher.go, pkg/gateway/proxy/dispatcher/proxylog.go, pkg/gateway/proxy/dispatcher/upgradeaware.go
/kind feature
feat(metrics): record all unexpected terminated proxy request
Fixes #
```release-note
```
=> feat(metrics): record all unexpected terminated proxy request

pkg/clusters/clusterinfo.go, pkg/clusters/features/features.go, pkg/gateway/proxy/dispatcher/dispatcher.go, pkg/gateway/proxy/dispatcher/status.go, plugin/admission/upstreamcluster/admission.go
/kind feature
add cluster level feature gate
Fixes #
```release-note
```
=> feat: add feature gate in cluster info

pkg/clusters/clusterinfo.go, pkg/clusters/features/features.go, pkg/clusters/features/features_test.go
>
> /kind bug
fix: correct the comparison of two feature gates
Fixes #
```release-note
```
=> fix: correct the comparison of two feature gates

pkg/gateway/proxy/dispatcher/proxylog.go
>
> /kind bug
add debug log for log running request
```release-note
```
=> debug: force print unexpected long running request

pkg/clusters/clusterinfo.go, pkg/clusters/endpoint.go, pkg/gateway/proxy/dispatcher/dispatcher.go, pkg/gateway/proxy/dispatcher/upgradeaware.go, pkg/transport/dynamic_impersonate.go
> /kind bug
use correct http1 upgrade transport in proxy handler
Fixes #
```release-note
```
=> fix: use correct http1 upgrade transport in proxy handler

cmd/kube-gateway/app/proxy.go
> /kind bug
redirect http log to klog
Fixes #
```release-note
```
=> fix: redirect http log to klog

go.mod, go.sum
> /kind bug
fix: trigger upstream health check immediately when start
Fixes 
```release-note
```
=> fix: upgrade http2 version

.gitignore, build/kube-gateway/Dockerfile, hack/lib/utils.sh, hack/local-up.sh
>
> /kind bug
Fixes #50
```release-note
```
=> fix hack/local-up.sh

cmd/kube-gateway/app/proxy.go, pkg/gateway/controlplane/bootstrap/hooks.go, pkg/gateway/controlplane/bootstrap/namespace.go, pkg/gateway/controlplane/server.go, pkg/gateway/metrics/metrics.go, pkg/gateway/metrics/obsever.go, pkg/gateway/metrics/prometheus.go, pkg/gateway/proxy/dispatcher/dispatcher.go
> /kind refactor
users can expand custom metric and bootstrap easily
Fixes #
```release-note
```
=> feat: refactor metrics and bootstrap

pkg/gateway/authentication/token/webhook/tokenreview.go, pkg/gateway/authorization/webhook/subjectaccessreview.go, pkg/gateway/endpoints/filters/metrics.go, pkg/gateway/endpoints/filters/requestinfo.go, pkg/gateway/endpoints/request/requestinfo.go, pkg/gateway/proxy/dispatcher/dispatcher.go
=> fix typo: Reqeust -> Request

pkg/clusters/clusterinfo.go, pkg/gateway/endpoints/filters/termination.go, pkg/gateway/endpoints/request/proxyInfo.go, pkg/gateway/metrics/metrics.go, pkg/gateway/metrics/obsever.go, pkg/gateway/metrics/prometheus.go, pkg/gateway/proxy/dispatcher/dispatcher.go, pkg/gateway/proxy/dispatcher/proxylog.go
>
add flowcontrol tag for proxy metric
Fixes #
```release-note
```
=> feat(metric): add flowcontrol tag

go.mod, go.sum
>
update go mod version to 1.18
Fixes #
```release-note
```
=> feat: update go version

cmd/kube-gateway/app/options/proxy.go, cmd/kube-gateway/app/options/validation.go, cmd/kube-gateway/app/proxy.go, pkg/flowcontrols/util/meter.go, pkg/gateway/endpoints/filters/goaway.go, pkg/gateway/endpoints/filters/requestrate.go, pkg/gateway/endpoints/filters/requestthroughput.go, pkg/gateway/endpoints/monitor/rate.go, pkg/gateway/endpoints/monitor/throughput.go, pkg/gateway/endpoints/response/termination.go, pkg/gateway/metrics/metrics.go, pkg/gateway/metrics/obsever.go, pkg/gateway/metrics/prometheus.go, pkg/gateway/proxy/dispatcher/dispatcher.go, pkg/gateway/proxy/dispatcher/status.go, pkg/gateway/proxy/options/server_run_options.go
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind flake
Fixes #
```release-note
```
=> feat: probabilistically send GOAWAY when proxy has load pressure

pkg/clusters/util.go
>
> /kind bug
add gateway pid to user-agent to distinguish different process
Fixes #
```release-note
```
=> feat: add gateway pid to user-agent

Makefile, hack/hooks/post-build, hack/lib/golang.sh, hack/lib/logging.sh, hack/make-rules/build.sh
>
> /kind build
remote dependence on personal build tools
Fixes #
```release-note
```
=> build: make-rules build script

pkg/gateway/endpoints/filters/upstreaminfo.go, pkg/gateway/endpoints/response/termination.go, pkg/gateway/proxy/dispatcher/dispatcher.go
ignore retry after for events to avoid too many retry requests
Fixes #
```release-note
```
=> feat: ignore retry after for events

pkg/gateway/metrics/prometheus.go
>
> /kind bug
remove path tag for termination metric to avoid oom
Fixes #
```release-note
```
=> feat: remove path tag for termination metric
